### ISSUE TITLE
时光相册API更换了，大佬考虑修复一下吗？

### ISSUE THREAD

**Issue by q3v5** [ICE99125/TimeAlbum#1]

**Comment by ICE99125** [comment]
你不说我都没发现😂

**Comment by q3v5** [comment]
> 你不说我都没发现joy

好像就是这两天更新一个新版本之后就失效了

**Comment by ICE99125** [comment]
好了，你试试吧

**Comment by RouJiANG-14** [comment]
大佬，改成青龙怎么做啊？？

**Comment by 56warmers** [comment]
> 大佬，改成青龙怎么做啊？？

青龙拉库后脚本列表不会读取到 push 目录，只会把目录下所有 py文件添加进来，所以 import 需要自己改
简单说下一种方式，不一定最优，但本人青龙 2.13.10 有效：
① ql repo 拉库
② index.py 文件头部改 from push import push 为你要的通知（如 from server import server ）；还要加一行从通知（ 如server ） from server import push 类（下一步粘贴的，导入一下）
③ 通知 py文件（如 server.py ）的 import 也要改，还要把 __ init __.py 里  import os  、push 类 粘贴进通知 py 文件
④ 设置环境变量，名称就是 key（如 server ）
⑤ config.py 里填账号密码，改 push 为你上面改的通知方式（如 server.py ）
⑥ 定时任务里添加 index.py 的调度任务，运行即可

**Comment by RouJiANG-14** [comment]
> > 大佬，改成青龙怎么做啊？？
> 
> 青龙拉库后脚本列表不会读取到 push 目录，只会把目录下所有 py文件添加进来，所以 import 需要自己改 简单说下一种方式，不一定最优，但本人青龙 2.13.10 有效： ① ql repo 拉库 ② index.py 文件头部改 from push import push 为你要的通知（如 from server import server ）；还要加一行从通知（ 如server ） from server import push 类（下一步粘贴的，导入一下） ③ 通知 py文件（如 server.py ）的 import 也要改，还要把 __ init __.py 里 import os 、push 类 粘贴进通知 py 文件 ④ 设置环境变量，名称就是 key（如 server ） ⑤ config.py 里填账号密码，改 push 为你上面改的通知方式（如 server.py ） ⑥ 定时任务里添加 index.py 的调度任务，运行即可


Traceback (most recent call last):
  File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 3, in <module>
    from server import server
  File "/ql/data/scripts/ICE99125_everphoto_checkin/server.py", line 3, in <module>
    from .workWeChat import workWechatRobot, workWechatApp
ImportError: attempted relative import with no known parent package

是我愚钝，照葫芦画瓢改了，运行报错。对不住了，大佬！

**Comment by 56warmers** [comment]
> 

哪有啥对不住的，python 比较好看明白，慢慢看着学就好了。

① 去青龙脚本管理确认下，相同的 repo 下（ICE99125_everphoto_checkin）有没有所需的 py 文件，相对引用貌似有报错。
② 前面你 import 的是 server ，为啥后面 import 的是 workWechatRobot ，逻辑要一致啊，这种改法就只用改一个通知的 py 文件，你要用 workWechatRobot 就把我举例的 server 全换成 workWechatRobot 。

**Comment by RouJiANG-14** [comment]
> > 大佬，改成青龙怎么做啊？？
> 
> 青龙拉库后脚本列表不会读取到 push 目录，只会把目录下所有 py文件添加进来，所以 import 需要自己改 简单说下一种方式，不一定最优，但本人青龙 2.13.10 有效： ① ql repo 拉库 ② index.py 文件头部改 from push import push 为你要的通知（如 from server import server ）；还要加一行从通知（ 如server ） from server import push 类（下一步粘贴的，导入一下） ③ 通知 py文件（如 server.py ）的 import 也要改，还要把 __ init __.py 里 import os 、push 类 粘贴进通知 py 文件 ④ 设置环境变量，名称就是 key（如 server ） ⑤ config.py 里填账号密码，改 push 为你上面改的通知方式（如 server.py ） ⑥ 定时任务里添加 index.py 的调度任务，运行即可

我放弃了通知....囧rz 就让它在后台默默签到吧。

**Comment by 56warmers** [comment]
> > > 大佬，改成青龙怎么做啊？？
> > 
> > 
> > 青龙拉库后脚本列表不会读取到 push 目录，只会把目录下所有 py 文件添加进来，所以 import 需要自己改 简单说下一种方式，不一定最优，但本人青龙 2.13.10 有效： ① ql repo 拉库 ② index.py 文件头部改 from push import push 为你要的通知（如 from server import server ）；还要加一行从通知（ 如 server ） from server import push 类（下一步粘贴的，导入一下） ③ 通知 py 文件（如 server.py ）的 import 也要改，还要把 __ init __.py 里 import os 、push 类 粘贴进通知 py 文件 ④ 设置环境变量，名称就是 key（如 server ） ⑤ config.py 里填账号密码，改 push 为你上面改的通知方式（如 server.py ） ⑥ 定时任务里添加 index.py 的调度任务，运行即可
> 
> 我放弃了通知.... 囧 rz 就让它在后台默默签到吧。

也可以，不管 push 也能完成签到，推送报错也没事。

**Comment by RouJiANG-14** [comment]
> > 
> 
> 哪有啥对不住的，python 比较好看明白，慢慢看着学就好了。
> 
> ① 去青龙脚本管理确认下，相同的 repo 下（ICE99125_everphoto_checkin）有没有所需的 py 文件，相对引用貌似有报错。 ② 前面你 import 的是 server ，为啥后面 import 的是 workWechatRobot ，逻辑要一致啊，这种改法就只用改一个通知的 py 文件，你要用 workWechatRobot 就把我举例的 server 全换成 workWechatRobot 。

我又尝试改了一下，提示这个。

Traceback (most recent call last):
  File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 42, in <module>
    main()
  File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 26, in main
    push(type, "时光相册", msg_list)
NameError: name 'push' is not defined

麻烦大佬再解释一下，再弄不好我就真放弃了。
这个push 是不是应该要在哪里定义引用一下，是不是要在index.py里 import push ？
我是在pushplus里做的import push。
看懂了一下，具体的定义调用还是不太理解。

**Comment by 56warmers** [comment]
> > > 
> > 
> > 
> > 哪有啥对不住的，python 比较好看明白，慢慢看着学就好了。
> > ① 去青龙脚本管理确认下，相同的 repo 下（ICE99125_everphoto_checkin）有没有所需的 py 文件，相对引用貌似有报错。 ② 前面你 import 的是 server ，为啥后面 import 的是 workWechatRobot ，逻辑要一致啊，这种改法就只用改一个通知的 py 文件，你要用 workWechatRobot 就把我举例的 server 全换成 workWechatRobot 。
> 
> 我又尝试改了一下，提示这个。
> 
> Traceback (most recent call last): File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 42, in main () File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 26, in main push (type, "时光相册", msg_list) NameError: name 'push' is not defined
> 
> 麻烦大佬再解释一下，再弄不好我就真放弃了。 这个 push 是不是应该要在哪里定义引用一下，是不是要在 index.py 里 import push ？ 我是在 pushplus 里做的 import push。 看懂了一下，具体的定义调用还是不太理解。

这里提示是找不到 push 类，你看我最开始说的②、③步，要把 __ init __.py 文件里的 push 类粘贴进去，还要 import 导入

**Comment by RouJiANG-14** [comment]
> > > > 
> > > 
> > > 
> > > 哪有啥对不住的，python 比较好看明白，慢慢看着学就好了。
> > > ① 去青龙脚本管理确认下，相同的 repo 下（ICE99125_everphoto_checkin）有没有所需的 py 文件，相对引用貌似有报错。 ② 前面你 import 的是 server ，为啥后面 import 的是 workWechatRobot ，逻辑要一致啊，这种改法就只用改一个通知的 py 文件，你要用 workWechatRobot 就把我举例的 server 全换成 workWechatRobot 。
> > 
> > 
> > 我又尝试改了一下，提示这个。
> > Traceback (most recent call last): File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 42, in main () File "/ql/data/scripts/ICE99125_everphoto_checkin/index.py", line 26, in main push (type, "时光相册", msg_list) NameError: name 'push' is not defined
> > 麻烦大佬再解释一下，再弄不好我就真放弃了。 这个 push 是不是应该要在哪里定义引用一下，是不是要在 index.py 里 import push ？ 我是在 pushplus 里做的 import push。 看懂了一下，具体的定义调用还是不太理解。
> 
> 这里提示是找不到 push 类，你看我最开始说的②、③步，要把 __ init __.py 文件里的 push 类粘贴进去，还要 import 导入

我不行了老哥，实在是搞不明白了，没有基础的我着实是个菜鸡，就放弃通知吧。反正要是没签到手机上APP也会提醒的。(捂脸笑.jpg
还是要感谢老哥！！不本来都放弃了，今天又尝试了一下，虽说不能通知，但是可以签到啊！哈哈哈。
